# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &laptop age1xewxg8sf4tr8m22dnwe40fc8vunt4fgu7j4xh4sxw9a9nz6ssy4q329rml
  - &desktop age1lut8udzmgyd4nj8p6pz485u8ae7crv7ck27j0jcn77kqw2k7rfgq0cuhna
creation_rules:
  # Common secrets
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *laptop
        - *desktop

  # Laptop-specific
  - path_regex: secrets/laptop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *laptop

  # Desktop-specific
  - path_regex: secrets/desktop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *desktop
